import {
  MusicNote,
  FilmSlate,
  Palette,
  BookOpen,
  Users,
  Microphone,
  Robot,
  MapTrifold,
  ForkKnife,
  Baby,
  Heartbeat,
  Megaphone,
  MaskHappy,
  Star,
  CalendarCheck,
  Leaf
} from "phosphor-react";

export const disciplinaIcons = {
  'Cine': FilmSlate,
  'Artes Escénicas': MaskHappy,
  'Música': MusicNote,
  'Artes Visuales': Palette,
  'Narración Oral': Microphone,
  'Conferencias': Megaphone,
  'Literatura': BookOpen,
  'Danza': Users,
  'Formación / Taller': CalendarCheck,
  'Cultura Tradicional': Star,
  'Itinerarios Patrimoniales': MapTrifold,
  'Público Infantil / Familiar': Baby,
  'Medio Ambiente': Leaf,
  'Salud y Bienestar': Heartbeat,
  'Tecnología / Innovación': Robot,
  'Gastronomía': ForkKnife,
  'Sociedad / Inclusión': Users,
  'Divulgación / Institucional': Megaphone,
  'Multidisciplinar': Users,
  'Actividades especiales': Star,
  'Eventos': CalendarCheck,
  'Deportes / Actividad Física': Users,
  'Otros': Users,
};

export const disciplinaColors = {
  'Cine': '#FFE4E1',
  'Artes Escénicas': '#E1F5FE',
  'Música': '#FFF9C4',
  'Artes Visuales': '#F8BBD0',
  'Narración Oral': '#FFECB3',
  'Conferencias': '#D1C4E9',
  'Literatura': '#B2DFDB',
  'Danza': '#FCE4EC',
  'Formación / Taller': '#FFCCBC',
  'Cultura Tradicional': '#DCEDC8',
  'Itinerarios Patrimoniales': '#C5CAE9',
  'Público Infantil / Familiar': '#FFCDD2',
  'Medio Ambiente': '#C8E6C9',
  'Salud y Bienestar': '#B3E5FC',
  'Tecnología / Innovación': '#E0F7FA',
  'Gastronomía': '#FFF8E1',
  'Sociedad / Inclusión': '#F1F8E9',
  'Divulgación / Institucional': '#F3E5F5',
  'Multidisciplinar': '#E6EE9C',
  'Actividades especiales': '#FFCCBC',
  'Eventos': '#FFE0B2',
  'Deportes / Actividad Física': '#FFB74D',
  'Otros': '#E0E0E0',
};
